### ISSUE TITLE
[INSTALL] identify if you should write to .bash_profile/.bashrc 

### ISSUE THREAD

**Issue by robsongajunior** [NascHQ/termtools#7]
## DESCRIPTION

- All of Linux versions has the .bashrc configuration file,
but, all MacOs and a few Linux has by default the .bash_profile file.

**Comment by robsongajunior** [comment]
PR OPENED: https://github.com/NascHQ/termtools/pull/5

**Comment by felipenmoura** [comment]
The PR was merged fixing this :)
