### ISSUE TITLE
aliases not working as the same in both linux and mac platforms

### ISSUE THREAD

**Issue by robsongajunior** [NascHQ/termtools#9]
## DESCRIPTION
- Some commands are not been finding.

### COMMANDS
- amionline (is not finishing the conf)
- amioffline (is not finishing the conf)
- ifactive (ifconfig/pcregrep command not fund)
- flush (bash: dscacheutil: command not found)

## QUESTION
- Why are you overwrittung rm command?

## TIPS
~ Maybe we sould to create a dependencies config file.

**Comment by felipenmoura** [comment]
hm, interesting indeed.
Some of those commands work only in mac. We have to "if" them for different platforms!

**Comment by felipenmoura** [comment]
We need to validade which of the aliases and functions are not working on linux, and fix it.
Can you help us list the problematic ones, @robsongajunior ?

**Comment by robsongajunior** [comment]
offcourse @felipenmoura, this week

**Comment by robsongajunior** [comment]
now... i will do a new check list...

**Comment by robsongajunior** [comment]
## CHANGED
- __ipin__
    - ifconfig should be performed with root previlegious, at debian the local ifconfig dont exist
- __hosts_edit__
    - created function to verify VIM installation, use VI case VIM missing
- __lsd__
    - --color is the valid param, --colors is invalid param

## ADDED
- __reloadbashrc__
    - following the reloadprofiler logic


## PROBLEM
- __flush__ and __flushDNS__ is not running
    - the reason is that dscacheutil - it is a apple development
- __amioffline/amionline__: always offline returning Yes and amionline No, the same whithout connection
- __ifactive__
    - pcregrep: Failed to open active: No such file or directory
- __pbcopy__
    - pbcoy it is to OS, to Debian/UBUNTU etc you should to use:

``` bash
sudo apt-get install xclip

# to create alias to pbcpy 
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
# now you are able to use the pbcopy to linux
```

- __datauri__
``` bash
bash: pbcopy: command not found
=> data URI copied to pasteboard.
base64: Cannot open input file , No such file or directory
base64: Use -help for summary.
```


## QUESTION
``` bash
alias ff='find . -not -path "*/node_modules/*" -not -path "*.git/*" -type f -iname '
alias findfile='ff'
alias fd='find . -not -path "*/node_modules/*" -not -path "*.git/*" -type d -iname '
alias finddir='fd'
```

The commands above, what should to happen? Maybe I mistake to run, findfile and finddir broke the terminal.

- __md5sum / shasum:__
   - i dont know what to to with that

## NOT DEFAULT
these commands it is avaiable only in MacOS

``` bash

# Show/hide hidden files in Finder
alias show-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Tip imported from Mathias Bynens' dotfiles
# https://github.com/mathiasbynens/dotfiles/blob/master/.aliases
# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'
# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
# Hide/show all desktop icons (useful when presenting)
alias hide-desktop-icons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias show-desktop-icons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder" 
```

**Comment by felipenmoura** [comment]
Awesome.
The pull request has been merged.

Any other linux user can confirm it's working well?

**Comment by robsongajunior** [comment]
i'm closing, my last pull request solved the tread
